services:

  user-service:
    build: ./User
    container_name: user-service
    ports:
      - "8082:8082"
    networks:
      - hotel-network

  hotel-service:
    build: ./Hotel
    container_name: hotel-service
    ports:
      - "8080:8080"
    networks:
      - hotel-network

  rating-service:
    build: ./Rating
    container_name: rating-service
    ports:
      - "8081:8081"
    networks:
      - hotel-network

  apigateway:
    build: ./ApiGateway
    container_name: apigateway
    ports:
      - "8083:8083"
    networks:
      - hotel-network

networks:
  hotel-network:
    driver: bridge