spring.application.name=Rating


# Server port
server.port=8081

# MySQL Database Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/rating?createDatabaseIfNotExist=true
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/rating?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect

# noinspection SpringBootApplicationProperties
#hotel.service.url=http://localhost:8080
#user.service.url=http://localhost:8082
hotel.service.url=http://hotel-service:8080
user.service.url=http://user-service:8082